### ISSUE TITLE
Pylint output for duplicate-code (R0801) violations is not parsed correctly

### ISSUE THREAD

**Issue by jzoldak** [edx/diff-cover#133]
The PylintQualityReporter has a single VIOLATION_REGEX = re.compile(r'^([^:]+):(\d+): \[(\w+),? ?([^\]]*)] (.*)$')

However this does not hold true in the case of duplicate-code (R0801) violations. Similarities are computed and displayed on closing, and have the following format. See pylint/checkers/similar.py.
```
tangentially_related_file.py:1: [R0801(duplicate-code)] Similar lines in N files
==offending_module_1:start_line_num_1
==offending_module_2:start_line_num_2
code that is duplicated
```
Thus if tangentially_related_file.py line 1 is determined to be part of the changeset, it is flagged as though it is the file in violation. And if a line in an actual offender is part of the changeset it will not be picked up anyhow.

**Comment by Bachmann1234** [comment]
I should be able to look at this in detail some time this week.

**Comment by jzoldak** [comment]
Thx @Bachmann1234!
No big rush on this side, I've disabled that code in our pylintrc so we are no longer running that checker.
It's a bit of a paradigm shift as there can no longer be a single matcher in this one case.

**Comment by Bachmann1234** [comment]
Howdy!

Just wanted to give you an update on this. I looked into it and managed to create a failing integration test demonstrating the issue. As you said this wont be a trivial fix. Hopefully I can find some time to dig into this more now that I think I got a grasp on it.

https://github.com/Bachmann1234/diff-cover/commit/baa0c396749b10f7a7aa6dde634ba4018311945a

**Comment by Bachmann1234** [comment]
@jzoldak howdy! I have a PR on my local branch that should fix this
https://github.com/Bachmann1234/diff-cover/pull/1 if you would like to review

The diff-cover project is a bit of a transition. edX was talking to me about my fork being made the official repo. I gotta see the status of that.

You open to testing this out in your environment after I release the fix?

**Comment by jzoldak** [comment]
@Bachmann1234 Sorry for the delay - I got caught up in vacations and snowstorms. I should be able to look into this later this week. Thx for figuring it out!

**Comment by jzoldak** [comment]
@Bachmann1234 ok all set. Looks like you and @wedaly have also transitioned over the official ownership to your fork. Will you be releasing a new version to pypi with the fix?

**Comment by Bachmann1234** [comment]
Yeah, ill make a release tonight

**Comment by Bachmann1234** [comment]
OK released! https://pypi.python.org/pypi/diff_cover/0.7.4 Try it out and if you're happy we can close the issue!
