### ISSUE TITLE
Html reporter can have trouble with binary files

### ISSUE THREAD

**Issue by benpatterson** [edx/diff-cover#140]
Hey @Bachmann1234 I spent a bit time looking at this today, but unfortunately I'm out of time.

We had a PR today ( https://github.com/edx/edx-platform/pull/6921 ) which introduced some binary files (including .bcmap and .png). These ended up causing failures when running diff-quality with the --html-report flag. (Without the flag, there are no errors). See console output here: https://build.testeng.edx.org/job/edx-platform-all-tests-pr/1202/SHARD=1,TEST_SUITE=quality,label_exp=jenkins-worker/console

Unfo it is a large commit and I was unable to isolate the offending file(s). I did attempt to reproduce this problem locally by creating a .bin and a .tar file, but I was unable to reproduce the error :( Thought, at best, I could log it here.

**Comment by Bachmann1234** [comment]
Howdy! I should be able to look into this. Can you reopen this on my fork? 
https://github.com/Bachmann1234/diff-cover

Future work goes there.

**Comment by Bachmann1234** [comment]
In unrelated terms. Holy hell that PR is huge. X-D

**Comment by benpatterson** [comment]
@Bachmann1234 Solid!

Opening an issue on your fork was my original intention, but unfortunately I didn't see a way to open issues on the fork, only PRs. Hopefully it's just a flag you can flip?

Yeah...that's one of the reasons I attempted to reproduce in a more straightforward manner, but no luck. Glancing at the unit tests, the snippets that are fed into the report generator tests are patched. Could be an option to put something binary through that pipe, but it looked like that would require some extra refactoring. Anyway sorry I don't have more time on my hands for it atm...

**Comment by Bachmann1234** [comment]
@benpatterson oh yes! My bad, That should be set now. I'll try and carve out time this week to try and figure this one out.

**Comment by benpatterson** [comment]
Awesome. Thanks @Bachmann1234 .

Closing this Issue in favor of https://github.com/Bachmann1234/diff-cover/issues/4 on Matt's fork (i.e. the new head)
